@startuml
!include style.puml
left to right direction
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-up-> "1" UniqueAssignmentList

UniqueAssignmentList -[hidden]down- UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList

UniqueAssignmentList -right-> "*" Assignment
UniqueTagList -right-> "*" Tag
UniquePersonList -right-> "*" Person

Person *-up-> "*" Tag
Person *-right-> "*" Assignment

Person *--> "1" PersonName
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" TuitionClass
Person *--> "1" Label

Assignment *-right-> "1" AssignmentName
@enduml
