@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-up-> "1" UniqueAssignmentList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueAssignmentList -right-> "*" Assignment
UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag
Person -right-> "*" Assignment

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> TuitionClass
@enduml
